---

- name: Create MAKER home dir
  file:
    path: "{{ MAKER_HOME }}"
    state: directory

- name: Download trf executable
  get_url:
    url: "{{ TRF_URL }}"
    dest: "/usr/local/bin/trf"
    mode: 0755

- name: Download RepeatMasker
  get_url:
    url: "{{ REPEAT_MASKER_URL }}"
    dest: "{{ MAKER_HOME }}/RepeatMasker-open-4-0-6.tar.gz"

- name: Unzip RepeatMasker
  unarchive:
    src: "{{ MAKER_HOME }}/RepeatMasker-open-4-0-6.tar.gz"
    dest: "{{ MAKER_HOME }}"
    remote_src: yes

# - name: Download RepBaseRepeatMaskerEdition
#   get_url:
#     url: "{{ REPBASE_GIRI_URL }}"
#     dest: "{{ MAKER_HOME }}/RepeatMasker/RepBaseRepeatMaskerEdition-20170127.tar.gz"
#
# - name: Unarchive RepBaseRepeatMaskerEdition
#   unarchive:
#     src: "{{ MAKER_HOME }}/RepeatMasker/RepBaseRepeatMaskerEdition-20170127.tar.gz"
#     dest: "{{ MAKER_HOME }}/RepeatMasker"
#     remote_src: yes
#
# - name: Copy and unarchive RepBaseRepeatMaskerEdition
#   unarchive:
#     src: "files/{{ REPBASE_FILE }}"
#     dest: "{{ MAKER_HOME }}/RepeatMasker"
#   when: REPBASE_FILE is defined

- name: Download DFAM library
  get_url:
    url: "{{ DFAM_LIB_URL }}"
    dest: "{{ MAKER_HOME }}/RepeatMasker/Dfam.hmm.gz"

- name: Unzip DFAM library
  command: "gunzip -f Dfam.hmm.gz"
  args:
    chdir: "{{ MAKER_HOME }}/RepeatMasker"

- name: Configure RepeatMasker
  shell: >
    printf '\n\n\n\n2\n/home/MAKER/ncbi-blast/c++/ReleaseMT/bin\n\n5\n' | perl ./configure
  args:
    chdir: "{{ MAKER_HOME }}/RepeatMasker"

- name: Add RepeatMasker to $PATH by adding line to bashrc
  lineinfile:
    path: "/home/{{ ATMOUSERNAME }}/.bashrc"
    line: "export PATH=\"{{ MAKER_HOME }}/RepeatMasker:$PATH\""
    state: present
    insertafter: EOF

- name: Cleanup
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ MAKER_HOME }}/RepeatMasker-open-4-0-6.tar.gz"
